replicaCount: 1
image:
  repository: ymevaser/customer-facing-api
  tag: "latest"  # Use a specific version tag if necessary
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80
containerPort: 3001
# Define any other configurations you need
ingress:
  enabled: false
  # annotations: {}
  # hosts:
  #   - host: chart-example.local
  #     paths:
  #     - path: /
  #       pathType: ImplementationSpecific
  # tls: []

autoscaling:
  enabled: false
  # minReplicas: 1
  # maxReplicas: 100
  # targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# ... more values like resources, autoscaling, etc.