# apiVersion: v1
# kind: Service
# metadata:
#   name: customer-facing-api-service
# spec:
#   selector:
#     app: customer-facing-api
#   ports:
#     - protocol: TCP
#       port: 80 # The service port
#       targetPort: 3001 # The container port
#   type: ClusterIP # Default type, only accessible within the cluster