apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-management-api
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/YigalMevaser/Unity.git
    path: ./server/customer-management-api
    targetRevision: develop
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true