apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "customer-management-api.fullname" . }}
  labels:
    {{- include "customer-management-api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "customer-management-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "customer-management-api.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          ports:
          - name: http
            containerPort: {{ .Values.containerPort }}