{{- if .Values.autoscaling.enabled }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ include "customer-management-api.fullname" . }}-scaler
  labels:
    {{- include "customer-management-api.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "customer-management-api.fullname" . }}
  minReplicaCount: {{ .Values.autoscaling.minReplicas }}
  maxReplicaCount: {{ .Values.autoscaling.maxReplicas }}
  triggers:
  - type: kafka
    metadata:
      bootstrapServers: {{ .Values.kafka.bootstrapServers }}
      topic: {{ .Values.kafka.topic }}
      consumerGroup: {{ .Values.kafka.consumerGroup }}
      lagThreshold: "{{ .Values.autoscaling.lagThreshold }}"
{{- end }}