apiVersion: v1
kind: Service
metadata:
  name: customer-management-api-service
spec:
  selector:
    app: customer-management-api
  ports:
    - protocol: TCP
      port: 80 # The service port
      targetPort: 3000 # The container port
  type: ClusterIP # Default type, only accessible within the cluster