apiVersion: v2
name: my-mongodb
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
   - name: mongodb
     version: "15.6.14" # Replace with the desired version of the MongoDB chart
     repository: "https://charts.bitnami.com/bitnami"