

# nameOverride: ""
# ## @param fullnameOverride String to fully override mongodb.fullname template
# ##
# fullnameOverride: ""
# ## @param namespaceOverride String to fully override common.names.namespace
# ##
# namespaceOverride: ""
# ## @param kubeVersion Force target Kubernetes version (using Helm capabilities if not set)
# ##

image:
  registry: docker.io
  repository: bitnami/mongodb
  tag: 7.0.12-debian-12-r0
  digest: ""
  
  pullPolicy: IfNotPresent
  
  pullSecrets: []
  
  debug: false

schedulerName: ""

architecture: standalone

useStatefulSet: false

auth:
  
  enabled: false
  
  

containerPorts:
  mongodb: 27017

livenessProbe:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 20
  timeoutSeconds: 10
  failureThreshold: 6
  successThreshold: 1

readinessProbe:
  enabled: true
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1

startupProbe:
  enabled: false
  initialDelaySeconds: 5
  periodSeconds: 20
  timeoutSeconds: 10
  successThreshold: 1
  failureThreshold: 30


service:
  port: 27017
  
  nameOverride: ""
  
  type: ClusterIP
  
  portName: mongodb
  
  ports:
    mongodb: 27017
  
  nodePorts:
    mongodb: ""
  
  clusterIP: ""
  
  externalIPs: []
  
  loadBalancerIP: ""
  
  loadBalancerClass: ""
  
  
  service:
    ## @param externalAccess.service.type Kubernetes Service type for external access. Allowed values: NodePort, LoadBalancer or ClusterIP
    ##
    type: LoadBalancer
    ## @param externalAccess.service.portName MongoDB(&reg;) port name used for external access when service type is LoadBalancer
    ##
    portName: "mongodb"
    ## @param externalAccess.service.ports.mongodb MongoDB(&reg;) port used for external access when service type is LoadBalancer
    ##
    ports:
      mongodb: 27017
    ## @param externalAccess.service.loadBalancerIPs Array of load balancer IPs for MongoDB(&reg;) nodes
    ## Example:
    ## loadBalancerIPs:
    ##   - X.X.X.X
    ##   - Y.Y.Y.Y
    ##
    loadBalancerIPs: []
    ## @param externalAccess.service.publicNames Array of public names. The size should be equal to the number of replicas.
    ##
    publicNames: []
    ## @param externalAccess.service.loadBalancerClass loadBalancerClass when service type is LoadBalancer
    # ref: https://kubernetes.io/docs/concepts/services-networking/service/#load-balancer-class
    loadBalancerClass: ""
    
    loadBalancerSourceRanges: []
    
    allocateLoadBalancerNodePorts: true
    
    externalTrafficPolicy: Local
    
    nodePorts: []
    
    domain: ""
    
    extraPorts: []
    
    annotations: {}
    
    annotationsList: []
    
    sessionAffinity: None
    
    sessionAffinityConfig: {}
 
  hidden:
    
    enabled: false
    
    service:
      
      type: LoadBalancer
      
      portName: "mongodb"
      
      ports:
        mongodb: 27017
   
      loadBalancerIPs: []
      
      loadBalancerClass: ""
   
      loadBalancerSourceRanges: []
      
      allocateLoadBalancerNodePorts: true
      
      externalTrafficPolicy: Local
      

serviceAccount:
  ## @param serviceAccount.create Enable creation of ServiceAccount for MongoDB(&reg;) pods
  ##
  create: true

ingress:
  enabled: false