name: Continuous Deployment

on: 
  release:
    types: [published]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    # Download artifacts
    - name: Download Kafka Artifact
      uses: actions/download-artifact@v2
      with:
        name: kafka
        path: ./artifacts

    - name: Download MongoDB Artifact
      uses: actions/download-artifact@v2
      with:
        name: mongodb
        path: ./artifacts

    - name: Download customer-facing-api Artifact
      uses: actions/download-artifact@v2
      with:
        name: customer-facing-api
        path: ./artifacts

    - name: Download customer-management-api Artifact
      uses: actions/download-artifact@v2
      with:
        name: customer-management-api
        path: ./artifacts

    # Assume the customer-facing-api and customer-management-api are Docker images
    - name: Load Docker Images
      run: |
        docker load < ./artifacts/customer-facing-api/customer-facing-api.tar
        docker load < ./artifacts/customer-management-api/customer-management-api.tar

    - name: Deploy Docker Containers
      run: |
        docker run -d --name customer-facing-api -p 80:80 your-docker-hub-username/customer-facing-api
        docker run -d --name customer-management-api -p 81:80 your-docker-hub-username/customer-management-api

    # Assume Kafka and MongoDB are Helm charts stored as tarballs
    - name: Deploy Kafka with Helm
      run: |
        helm repo add myrepo https://my.chart.repo
        helm install kafka ./artifacts/kafka/kafka-chart.tar.gz

    - name: Deploy MongoDB with Helm
      run: |
        helm install mongodb ./artifacts/mongodb/mongodb-chart.tar.gz