name: CI/CD Pipeline

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      stage:
        description: 'Stage to run (build/deploy/all)'
        required: true
        default: 'all'

jobs:
  build:
    if: github.event_name != 'workflow_dispatch' || github.event.inputs.stage == 'build' || github.event.inputs.stage == 'all'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Helm
      uses: azure/setup-helm@v1

    - name: Install Dependencies for Customer Facing API
      run: helm dependency update ./client/customer-facing-api

    - name: Install Dependencies for Customer Management API
      run: helm dependency update ./server/customer-management-api

    - name: Install Dependencies for Kafka
      run: helm dependency update ./kafka-helm
     
    - name: Init Helm Repositories
      run: helm init --stable-repo-url=https://charts.helm.sh/stable

    - name: Add Helm Repositories
      run: helm repo add bitnami https://charts.bitnami.com/bitnami

    - name: Update Helm Repositories
      run: helm repo update      

    - name: Install Dependencies for MongoDB
      run: helm dependency update ./mongodb/my-mongodb   

    - name: Build Customer Facing API
      run: echo "Building Customer Facing API..."

    - name: Build Customer Management API
      run: echo "Building Customer Management API..."

    - name: Build Kafka
      run: echo "Building Kafka"    

    - name: Build MongoDB
      run: echo "Building MongoDB"    

    - name: Publish Customer Facing API Artifact
      uses: actions/upload-artifact@v4
      with:
        name: customer-facing-api
        path: ./client/customer-facing-api

    - name: Publish Customer Management API Artifact
      uses: actions/upload-artifact@v4
      with:
        name: customer-management-api
        path: ./server/customer-management-api

    - name: Publish Kafka Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Kafka
        path: ./kafka-helm

    - name: Publish MongoDB Artifact
      uses: actions/upload-artifact@v4
      with:
        name: MongoDB
        path: ./mongodb/my-mongodb

  deploy:
    needs: build
    if: github.event_name != 'workflow_dispatch' || github.event.inputs.stage == 'deploy' || github.event.inputs.stage == 'all'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download Customer Facing API Artifact
      uses: actions/download-artifact@v2
      with:
        name: customer-facing-api
        path: ./client/customer-facing-api

    - name: Download Customer Management API Artifact
      uses: actions/download-artifact@v2
      with:
        name: customer-management-api
        path: ./server/customer-management-api

    - name: Download Kafka Artifact
      uses: actions/download-artifact@v2
      with:
        name: Kafka
        path: ./kafka-helm

    - name: Download MongoDB Artifact
      uses: actions/download-artifact@v2
      with:
        name: MongoDB
        path: ./mongodb/my-mongodb

    - name: Load Docker Images
      run: |
        docker load < ./artifacts/client/customer-facing-api/customer-facing-api.tar
        docker load < ./artifacts/server/customer-management-api/customer-management-api.tar

    - name: Deploy Docker Containers
      run: |
        docker run -d --name customer-facing-api -p 80:80 ymevaser/customer-facing-api
        docker run -d --name customer-management-api -p 81:80 ymevaser/customer-management-api

    - name: Deploy Kafka with Helm
      run: |
        helm repo add myrepo https://my.chart.repo
        helm install kafka ./kafka-helm/kafka-chart.tar.gz

    - name: Deploy MongoDB with Helm
      run: |
        helm install mongodb ./mongodb/my-mongodb/mongodb-chart.tar.gz