name: Continuous Integration

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Helm
      uses: azure/setup-helm@v1

    - name: Install Dependencies for Customer Facing API
      run: helm dependency update ./client/customer-facing-api

    - name: Install Dependencies for Customer Management API
      run: helm dependency update ./server/customer-management-api

    - name: Install Dependencies for Kafka
      run: helm dependency update ./kafka-helm

    - name: Update Helm Repositories
      run: helm repo add "stable" "https://charts.helm.sh/stable" --force-update
    
    - name: Update Helm Repositories
      run: helm init


    - name: Install Dependencies for MongoDB
      run: helm dependency update ./mongodb/my-mongodb   

    - name: Build Customer Facing API
      run: |
        # Replace the next line with the actual build command for your API
        echo "Building Customer Facing API..."

    - name: Build Customer Management API
      run: |
        # Replace the next line with the actual build command for your API
        echo "Building Customer Management API..."

    - name: Build Kafka
      run: |
        # Replace the next line with the actual build command for your API
        echo "Building Kafka"    

    - name: Build MongoDB
      run: |
        # Replace the next line with the actual build command for your API
        echo "Building MongoDB"    

    # If there are tests or other checks, include them here

    - name: Publish Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: customer-facing-api
        path: ./client/customer-facing-api

    - name: Publish Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: customer-management-api
        path: ./server/customer-management-api

    - name: Publish Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Kafka
        path: ./kafka-helm

    - name: Publish Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: MongoDB
        path: ./mongodb/my-mongodb          